@End2End
Feature: 04 SMB End2End feature

  Background: Setup background and environment
    Given I setup browser
    Then I setup appian URL to "appian.active.url"
    And I setup appian version
    And I setup appian locale

  Scenario: TC001_Trust_Verify Introducer is able to Request a quote and Submit the application for New Asset and Dealer Pricing with Operating Lease for Passenger or LCV
    Given I setup environment and login with role "introducer"
    Given I load test data for "TC001" from "04_SMB_End2End"
    Then I click on button "Request A Quote"
    Then I populate field "Search Journeys" with excel "excel:ABN"
    Then I click on button "SEARCH[2]"
    Then I select grid "[2]" row "[1]"
    Then I click on button "Next"
    Then I click on element with text from excel "excel:What type of asset are you seeking to finance?"
    Then I click on element with text from excel "excel:Do you have a specific passenger or light commercial vehicle in mind?"
    Then I click on element with text from excel "excel:Is the passenger or light commercial vehicle new?"
    Then I click on element with text from excel "excel:Do you want to use ORIX pricing?"
    Then I click on card direct from excel "excel:What product suits you best?"
    Then I populate field "Make" with excel "excel:Make"
    Then I populate field "Model" with excel "excel:Model"
    Then I populate field "Sub Model" with excel "excel:Sub Model"
    Then I click on button "SEARCH[2]"
    Then I click on button "SELECT VEHICLE"
    Then I populate field "Colour" with excel "excel:Colour"
    Then I populate field "Trim" with excel "excel:Trim"
    Then I populate field "Term" with excel "excel:Select a Term"
    Then I wait for "2" seconds
    Then I populate field "Annual Usage[3]" with excel "excel:Annual Usage"
    Then I populate field "Delivery State" with excel "excel:Delivery State"
    Then I populate field "Dealer Quote" with excel "excel:Quote Document"
    Then I populate field "Vehicle Category" with excel "excel:Vehicle or Asset Category"
    Then I populate field "Total Cost of Accessories (excl GST)" with excel "excel:Total Cost of Accessories (excl GST)"
    Then I populating field "Plate Cost (excl GST)" with excel "excel:Plate Cost (excl GST)"
    Then I populate field "Dealer Origination Fee" with excel "excel:Dealer Origination Fee (excl. GST)"
    Then I populate field "Discounts (excl GST)" with excel "excel:Discounts (excl GST)"
    Then I populate field "Stamp Duty (excl GST)" with excel "excel:Stamp Duty (excl GST)"
    Then I populate field "Luxury Car Tax (excl GST)" with excel "excel:Luxury Car Tax (excl GST)"
    Then I populate field "Registration Fee (excl GST)" with excel "excel:Registration Fee (excl GST)"
    Then I populate field "CTPI Fee (excl GST)" with excel "excel:CTPI Fee (excl GST)"
    Then I populate field "Delivery Fee (excl GST)" with excel "excel:Delivery Fee (excl GST)"
    Then I click on button "Next"
    Then I click on element with text from excel "excel:Services"
    Then I wait for "3" seconds
    Then I click on button "Generate Quote"
    Then I verify text "Indicative Quote Summary" is present
    Then I verify text "Operating Lease" is present
    Then I verify text "Your Passenger or Light Commercial Vehicle" is present
    Then I verify text "Passenger or Light Commercial Vehicle Description" is present
    Then I verify text "Total Cost of Lease" is present
    Then I verify text "Total Asset Cost (incl GST)" is present
    Then I click on button "Close"
    Then I wait for "3" seconds
    Then I click on button "Proceed Quote"
    Then I click on element with text from excel "excel:Application Type"
    Then I click on button "Next"
#   Applicant Company Details tab Inputs and data verification
    Then I verify field "ABN" contains excel "excel:ABN"
    Then I verify field "Business Name" contains excel "excel:Registered Business Name"
    Then I verify field "ACN" contains excel "excel:ACN"
    Then I verify field "Company Name" contains excel "excel:Company Name"
    Then I verify field "Business Address" contains excel "excel:Business Address"
    Then I verify field "Company Website" contains excel "excel:Company Website"
    Then I verify field "Industry ANZSIC Code" contains excel "excel:Industry ANZSIC Code"
    Then I verify field "Industry Classification" contains excel "excel:Industry Classification"
    Then I populate field "Business Background" with excel "excel:Business Background"
    Then I populate field "Asset Purpose" with excel "excel:Asset Purpose"
    Then I click on button "Next"
#    Financial tab Inputs and data verification
    Then I verify field "Income" contains excel "excel:Income"
    Then I verify field "Expenses" contains excel "excel:Expenses"
    Then I verify field "Income Frequency" contains excel "excel:Income Frequency"
    Then I verify field "Expenses Frequency" contains excel "excel:Expenses Frequency"
    Then I click on button "Next"
#    Owner Individuals tab Inputs and data verification
    Then I verify text "Please identify any individuals who may be a Director, Shareholder, Beneficial Owner, and/or Guarantor to your company" is present
    Then I verify text "Applications without a Director's Guarantee will require further assessment, you will be required to provide 3 years worth of financial statements." is present
    Then I verify field "First Name" contains excel "excel:First Name"
    Then I verify field "Last Name" contains excel "excel:Last Name"
    Then I click on button "Next"
    Then I verify field "First Name" contains excel "excel:First Name"
    Then I verify field "Last Name" contains excel "excel:Last Name"
    Then I verify field "Gender" contains excel "excel:Gender"
    Then I verify field "Date Of Birth" contains excel "excel:Date Of Birth"
    Then I verify field "Citizenship Status" contains excel "excel:Citizenship Status"
    Then I verify field "Residential Status" contains excel "excel:Residential Status"
    Then I verify field "Phone Number" contains excel "excel:Phone Number"
    Then I verify field "Email" contains excel "excel:Email"
    Then I verify field "License Type" contains excel "excel:License Type"
    Then I verify field "License Class" contains excel "excel:License Class"
    Then I verify field "License State" contains excel "excel:License State"
    Then I verify field "Licence Number" contains excel "excel:Drivers Licence Number"
    Then I click on button "Next"
    Then I verify field "ABN" contains "66004759611"
    Then I verify field "ACN" contains "004759611"
    Then I verify field "Company Name" contains "HONDA AUSTRALIA PTY. LTD."
    Then I click on button "Next"
    Then I verify text "Please identify any additional trusts who may be a Shareholder and/or Guarantor to your company" is present
    Then I verify field "ABN" contains "45004189708"
    Then I verify field "Trust Name" contains "COLES SUPERMARKETS AUSTRALIA PTY LTD"
    Then I click on button "Next"
#   Summary tab Inputs and data verification
    Then I verify field "Company Name" contains excel "excel:Company Name"
    Then I verify field "ABN" contains excel "excel:ABN"
    Then I verify field "ACN" contains excel "excel:ACN"
    Then I verify field "Business Name" contains excel "excel:Registered Business Name"
    Then I verify field "Company Website" contains excel "excel:Company Website"
    Then I verify field "Income" contains excel "excel:Income"
    Then I verify field "Expenses" contains excel "excel:Expenses"
    Then I verify field "Income Frequency" contains excel "excel:Income Frequency"
    Then I verify field "Expenses Frequency" contains excel "excel:Expenses Frequency"
    Then I verify text "Applications without a Director's Guarantee will require further assessment, you will be required to provide 3 years worth of financial statements." is present
    Then I verify field "First Name" contains excel "excel:First Name"
    Then I verify field "Last Name" contains excel "excel:Last Name"
    Then I click on checkbox option "[1]"
    Then I click on checkbox option "[2]"
    Then I click on checkbox option "[3]"
    Then I click on checkbox option "[4]"
    Then I click on button "Submit"
    Then I wait for "2" seconds
    Then I click on element with text "BEGIN[2]"
    Then I click on element with text "Send SMS"
    Then I verify text "The link sent via SMS will be active for 48 hours." is present
    Then I populates field "File Upload[20]" with excel "excel:Privacy Consent Form"
    Then I click on button "Submit"
    Then I wait for "2" seconds
    Then I get grid "" column "Application Number" row "1" value and store in excel "excel:Application Number"
    Then I get grid "" column "Quote Number" row "1" value and store in excel "excel:Quote Number"
    Then I get grid "" column "Client (Applicant)" row "1" value and store in excel "excel:Client or Applicant"
    Then I get grid "" column "Application Status" row "1" value and store in excel "excel:Application Status"
    Then I get grid "" column "Date Created" row "1" value and store in excel "excel:Date Created"
    Then I get grid "" column "Last Updated User" row "1" value and store in excel "excel:Last Updated User"

  Scenario: TC002_Trust_Verify creditManager is able to Relinquish Ownership and Allocate the Application
    Given I setup environment and login with role "creditManager"
    Given I load test data for "TC002" from "04_SMB_End2End"
    When I click on record from excel "excel:Application Number"
#  Applicant Company Details verification
    Then I verify field "Company Name" contains excel "excel:Company Name"
    Then I verify field "ABN" contains excel "excel:ABN"
    Then I verify field "ACN" contains excel "excel:ACN"
    Then I verify field "Business Name" contains excel "excel:Registered Business Name"
    Then I verify field "Business Address" contains excel "excel:Business Address"
    Then I verify field "GST Registration Date" contains excel "excel:GST Registration Date"
    Then I verify field "Company Website" contains excel "excel:Company Website"
    Then I verify field "Industry ANZSIC Code" contains excel "excel:Industry ANZSIC Code"
    Then I verify field "Industry Classification" contains excel "excel:Industry Classification"
    Then I verify field "Business Background" contains excel "excel:Business Background"
    Then I verify field "Asset Purpose" contains excel "excel:Asset Purpose"
#  Financial Details verification
    Then I verify field "Income" contains excel "excel:Income"
    Then I verify field "Expenses" contains excel "excel:Expenses"
    Then I verify field "Income Frequency" contains excel "excel:Income Frequency"
    Then I verify field "Expenses Frequency" contains excel "excel:Expenses Frequency"
#  Owners - Individuals Details verification
    Then I verify text "Applications without a Director's Guarantee will require further assessment, you will be required to provide 3 years worth of financial statements." is present
    Then I verify field "First Name" contains excel "excel:First Name"
    Then I verify field "Last Name" contains excel "excel:Last Name"
    Then I verify field "Roles" contains excel "excel:Roles"
    Then I verify field "Citizenship Status" contains excel "excel:Citizenship Status"
    Then I verify field "Residential Status" contains excel "excel:Residential Status"
    Then I verify field "Gender" contains excel "excel:Gender"
    Then I verify field "Residential Address" contains excel "excel:Residential Address"
    Then I verify field "Phone Number[2]" contains excel "excel:Phone Number"
    Then I verify field "Email" contains excel "excel:Email"
    Then I verify field "License Type" contains excel "excel:License Type"
    Then I verify field "License Class" contains excel "excel:License Class"
    Then I verify field "License State" contains excel "excel:License State"
    Then I verify field "Licence Number" contains excel "excel:Drivers Licence Number"
    #  Company Information 1 Details verification
    Then I verify text "Company 1" is present
    Then I verify field "ABN[3]" contains "66004759611"
    Then I verify field "ACN[2]" contains "004759611"
    Then I verify field "Company Name[2]" contains "HONDA AUSTRALIA PTY. LTD."
    Then I verify field "Roles[2]" contains "Shareholder"
    #  Owners - Trusts 1 Details verification
    Then I verify text "Trust 1" is present
    Then I verify field "ABN[4]" contains "45004189708"
    Then I verify field "Trust Name" contains "COLES SUPERMARKETS AUSTRALIA PTY LTD"
    Then I verify field "Roles[3]" contains "Guarantor"
#  Right side pane Details verification
    Then I verify text "Overall Decision" is present
    Then I verify text "Owner" is present
    Then I verify text "Funding Value" is present
    Then I verify text "Monthly Repayment" is present
    Then I verify text "Customer Tier" is present
    Then I verify text "Application Criteria" is present
    Then I verify text "Low-Doc" is present
    #   Verifying content on 'Credit Rules'
    Then I click on record view "Credit Rules"
    Then I wait for "3" seconds
    Then I verify grid "" column "Name" row "[1]" contains "ABN Age"
    Then I verify grid "" column "Rule Description" row "[1]" contains "ABN age is older than 1 year"
    Then I verify grid "" column "Result" row "[1]" contains "Approved"
    Then I verify grid "" column "Name" row "[2]" contains "Max Loan Amount"
    Then I verify grid "" column "Rule Description" row "[2]" contains "Total Loan Amount is less than $200,000"
    Then I verify grid "" column "Result" row "[2]" contains "Approved"
    Then I verify grid "" column "Name" row "[3]" contains "Credit File Age"
    Then I verify grid "" column "Rule Description" row "[3]" contains "Credit file age is equal to or greater than 12 months"
    Then I verify grid "" column "Value" row "[3]" contains "-"
    Then I verify grid "" column "Result" row "[3]" contains "Referred"
    Then I verify grid "" column "Name" row "[4]" contains "Credit File Activity"
    Then I verify grid "" column "Rule Description" row "[4]" contains "Credit file has activity recorded in the past 24 months from date of submission for current credit application"
    Then I verify grid "" column "Value" row "[4]" contains "-"
    Then I verify grid "" column "Result" row "[4]" contains "Referred"
    Then I verify grid "" column "Name" row "[5]" contains "Adverse Credit File"
    Then I verify grid "" column "Rule Description" row "[5]" contains "Applicant has no adverse on their credit file"
    Then I verify grid "" column "Value" row "[5]" contains "-"
    Then I verify grid "" column "Result" row "[5]" contains "Referred"
    Then I verify grid "" column "Name" row "[6]" contains "Lending Enquiries"
    Then I verify grid "" column "Rule Description" row "[6]" contains "Applicant has made more than 5 lending enquiries in the past 30 days and more than 20 in the last 180 days. "
    Then I verify grid "" column "Value" row "[6]" contains "-"
    Then I verify grid "" column "Result" row "[6]" contains "Referred"
    Then I verify grid "" column "Name" row "[7]" contains "Court Writs/Actions"
    Then I verify grid "" column "Rule Description" row "[7]" contains "Applicant has no Court Writ and/or Court Action on their credit file"
    Then I verify grid "" column "Value" row "[7]" contains "-"
    Then I verify grid "" column "Result" row "[7]" contains "Referred"
    Then I verify grid "" column "Name" row "[8]" contains "Credit Score (Tier A)"
    Then I verify grid "" column "Rule Description" row "[8]" contains "Credit Score is greater than 549"
    Then I verify grid "" column "Value" row "[8]" contains "-"
    Then I verify grid "" column "Result" row "[8]" contains "Referred"
    Then I verify grid "" column "Name" row "[9]" contains "ASIC File Status"
    Then I verify grid "" column "Rule Description" row "[9]" contains "Applicant ASIC File Status is 'Pending'"
    Then I verify grid "" column "Value" row "[9]" contains "False"
    Then I verify grid "" column "Result" row "[9]" contains "Approved"
    Then I verify grid "" column "Name" row "[10]" contains "Equifax - Individual Guarantor"
    Then I verify grid "" column "Rule Description" row "[10]" contains "Individual guarantors have been identified. Please view the associated Consumer and Commercial Report"
    Then I verify grid "" column "Value" row "[10]" contains "True"
    Then I verify grid "" column "Result" row "[10]" contains "Referred"
    Then I verify grid "" column "Name" row "[11]" contains "Green ID - Identity Verification"
    Then I verify grid "" column "Rule Description" row "[11]" contains "Identity verification pass on GreenID"
    Then I verify grid "" column "Value" row "[11]" contains "True"
    Then I verify grid "" column "Result" row "[11]" contains "Approved"
    Then I verify grid "" column "Name" row "[12]" contains "Green ID - PEP/Sanction check"
    Then I verify grid "" column "Rule Description" row "[12]" contains "No match found on PEP/Sanctions check"
    Then I verify grid "" column "Value" row "[12]" contains "True"
    Then I verify grid "" column "Result" row "[12]" contains "Approved"
    Then I verify grid "" column "Name" row "[13]" contains "Beneficial Owners Review Required"
    Then I verify grid "" column "Rule Description" row "[13]" contains "Applicant is a private company with at least one organisation listed as a shareholder. Please review the Beneficial Owners Report"
    Then I verify grid "" column "Value" row "[13]" contains "False"
    Then I verify grid "" column "Result" row "[13]" contains "Approved"
    Then I verify grid "" column "Name" row "[14]" contains "Company Guarantors"
    Then I verify grid "" column "Rule Description" row "[14]" contains "At least one guarantor has been identified as a company. Please review the guarantors Company Scored Enquiry Report"
    Then I verify grid "" column "Value" row "[14]" contains "False"
    Then I verify grid "" column "Result" row "[14]" contains "Approved"
    Then I verify grid "" column "Name" row "[15]" contains "ANZSIC Code"
    Then I verify grid "" column "Rule Description" row "[15]" contains "ANZSIC Industry classification does not meet ORIX policy"
    Then I verify grid "" column "Value" row "[15]" contains "False"
    Then I verify grid "" column "Result" row "[15]" contains "Approved"
    Then I verify grid "" column "Name" row "[16]" contains "Mercantile Agent Enquiries"
    Then I verify grid "" column "Rule Description" row "[16]" contains "Applicant has no  Mercantile Agent Enquiries < 12 months on their credit file"
    Then I verify grid "" column "Value" row "[16]" contains "False"
    Then I verify grid "" column "Result" row "[16]" contains "Referred"
    Then I verify grid "" column "Name" row "[17]" contains "Payment Defaults"
    Then I verify grid "" column "Rule Description" row "[17]" contains "Applicant has no Payment Defaults on their credit file"
    Then I verify grid "" column "Value" row "[17]" contains "True"
    Then I verify grid "" column "Result" row "[17]" contains "Approved"
    Then I verify grid "" column "Name" row "[18]" contains "Directors Adverse"
    Then I verify grid "" column "Rule Description" row "[18]" contains "Applicant has no  Company Director's Adverse on their credit file"
    Then I verify grid "" column "Value" row "[18]" contains "False"
    Then I verify grid "" column "Result" row "[18]" contains "Referred"
    Then I verify grid "" column "Name" row "[19]" contains "Directors Adverse (Related Entity)"
    Then I verify grid "" column "Rule Description" row "[19]" contains "Applicant has no Company Director's Related Entity Adverse on their credit file"
    Then I verify grid "" column "Value" row "[19]" contains "False"
    Then I verify grid "" column "Result" row "[19]" contains "Referred"
    Then I verify grid "" column "Name" row "[20]" contains "External Administrators"
    Then I verify grid "" column "Rule Description" row "[20]" contains "Applicant has no  External Administrators on their credit file"
    Then I verify grid "" column "Value" row "[20]" contains "True"
    Then I verify grid "" column "Result" row "[20]" contains "Approved"
    Then I verify grid "" column "Name" row "[21]" contains "Petitions"
    Then I verify grid "" column "Rule Description" row "[21]" contains "Applicant has no Petitions on their credit file"
    Then I verify grid "" column "Value" row "[21]" contains "True"
    Then I verify grid "" column "Result" row "[21]" contains "Approved"
    Then I verify grid "" column "Name" row "[22]" contains "Company Sub-Class"
    Then I verify grid "" column "Rule Description" row "[22]" contains "Applicant ASIC File Sub-Class is 'Proprietary Company'"
    Then I verify grid "" column "Value" row "[22]" contains "False"
    Then I verify grid "" column "Result" row "[22]" contains "Referred"
    Then I verify grid "" column "Name" row "[23]" contains "Application Criteria"
    Then I verify grid "" column "Rule Description" row "[23]" contains "The Application falls under the Low Doc criteria"
    Then I verify grid "" column "Value" row "[23]" contains "True"
    Then I verify grid "" column "Result" row "[23]" contains "Approved"
    Then I verify grid "" column "Name" row "[24]" contains "Luxury Vehicle (New)"
    Then I verify grid "" column "Rule Description" row "[24]" contains "Asset being financed is a New Passenger Car valued over $160K."
    Then I verify grid "" column "Value" row "[24]" contains "False"
    Then I verify grid "" column "Result" row "[24]" contains "Approved"
    Then I verify grid "" column "Name" row "[25]" contains "NZ Citizen"
    Then I verify grid "" column "Rule Description" row "[25]" contains "An Individual with NZ Citizenship has been identified"
    Then I verify grid "" column "Value" row "[25]" contains "False"
    Then I verify grid "" column "Result" row "[25]" contains "Approved"
    Then I verify grid "" column "Name" row "[26]" contains "Overall Decision"
    Then I verify grid "" column "Result" row "[26]" contains "Referred"
    Then I click on button "Individual Guarantor - John Wickner"
    Then I wait for "2" seconds
    Then I verify grid "" column "Name" row "[1]" contains "Credit File Age"
    Then I verify grid "" column "Rule Description" row "[1]" contains "Credit file age is equal to or greater than 12 months"
    Then I verify grid "" column "Result" row "[1]" contains "Referred"
    Then I verify grid "" column "Name" row "[2]" contains "Overall Decision"
    Then I verify grid "" column "Result" row "[2]" contains "Referred"
    Then I click on record view "Identity Verification - Applicant"
#    Verifying content on 'Identity Verification - Applicant'
    Then I verify text "This application has not initiated their Identity Verification" is present
    Then I click on record view "Identity Verification - Proprietors"
    Then I verify text "No additional individuals have listed on this application have initiated their Identity Verification" is present
#    Verifying content on 'Identity Verification - Proprietors'
    Then I click on record view "Credit Report - Applicant"
#    Verifying content on 'Credit Report - Applicant'
    Then I verify text "No Equifax Credit Reports to Display for this application." is present
    Then I click on record view "Beneficial Owner Report - Applicant"
    Then I click on record view "Credit Report - Guarantors"
    Then I verify grid "" column "Name of the Guarantor" row "[1]" contains "John Wickner"
    Then I verify grid "" column "Credit Report Name(s)" row "[1]" contains "Equifax Commercial Individual Report"
    Then I verify grid "" column "Status" row "[1]" contains "Success"
    Then I click on record view "Document Extraction"
    Then I verify text "No items available" is present
    Then I click on record view "Documents"
#    Verifying content on 'Documents'
    Then I verify text "Uploaded Documents" is present
    Then I verify grid "" column "Document Name" row "[1]" contains "Privacy_Consent_Form.pdf"
    Then I verify grid "" column "Document Type" row "[1]" contains "Privacy Consent Form"
    Then I verify grid "" column "Uploaded By" row "[1]" contains "Automation Introducer"
    Then I click on record view "Communications"
    Then I verify text "No items available" is present
    Then I click on record view "Event History"
#    Verifying content on 'Event History'
    Then I verify text "Created Application" is present
    Then I verify text "Signed Privacy Statement" is present
    Then I verify text "Updated Application" is present
    Then I click on record view "Quote Details"
#    Verifying content on 'Quote Details'
    Then I verify text "Operating Lease" is present
    Then I verify text "HONDA CR-V" is present
    Then I verify field "Total Asset Cost" contains excel "excel:Total Asset Cost (incl. GST)"
    Then I verify field "GST" contains excel "excel:Total GST"
    Then I verify field "Total Cost of Lease" contains excel "excel:Total Cost of Lease"
    Then I verify field "Monthly Rental" contains excel "excel:Monthly Rental"
    Then I verify field "Specific Asset" contains excel "excel:Specific Asset"
    Then I verify field "New Asset" contains excel "excel:New Asset"
    Then I verify field "Pricing Type" contains excel "excel:Pricing Type"
    Then I verify field "Asset Type" contains excel "excel:Asset Type"
    Then I verify field "Monthly GST" contains excel "excel:Monthly GST"
    Then I verify field "Total GST" contains excel "excel:Total GST"
    Then I verify field "Residual Percentage" contains excel "excel:Residual Percentage"
    Then I verify field "Asset Category[2]" contains excel "excel:Vehicle or Asset Category"
    Then I verify field "Business" contains excel "excel:Company Name"
    Then I verify field "Introducer" contains "Dandenong Mits Pty Ltd"
    Then I verify field "Annual Usage" contains excel "excel:Annual Usage"
    Then I verify field "Discounts (excl GST)" contains excel "excel:Discounts (excl GST)"
    Then I verify field "Registration fee (excl GST)" contains excel "excel:Registration Fee (excl GST)"
    Then I verify field "Delivery State" contains excel "excel:Delivery State"
    Then I verify field "Status" contains excel "excel:Status"
    Then I verify field "Dealer Quote Document" contains excel "excel:Dealer Quote Document"
    Then I click on record view "Summary"
    Then I click on button "Take Ownership"
    Then I wait for "2" seconds
    Then I click on button "Done"
    Then I verify text "Automation Credit Manager" is present
    Then I wait for "2" seconds
    Then I click on button with tooltip "More actions"
    Then I click on element with text "Relinquish Ownership"
    Then I click on button "Done"
    Then I verify text "Unassigned" is present
    Then I click on button "Allocate Application"
    Then I wait for "3" seconds
    Then I verify text "Allocate Credit Application" is present
    Then I populate field "Credit Officer" with excel "excel:Credit Officer"
    Then I click on button "Submit"
    Then I verify text "Overall Decision" is present
    Then I verify text "Referred" is present
    Then I verify text "Automation Credit Reviewer" is present


  Scenario: TC003_Trust_Verify creditReviewer is able to overwrite credit decision for Trust
    Given I setup environment and login with role "creditReviewer"
    Given I load test data for "TC003" from "04_SMB_End2End"
    When I click on record from excel "excel:Application Number"
#  Applicant Company Details verification
    Then I verify field "Company Name" contains excel "excel:Company Name"
    Then I verify field "ABN" contains excel "excel:ABN"
    Then I verify field "ACN" contains excel "excel:ACN"
    Then I verify field "Business Name" contains excel "excel:Registered Business Name"
    Then I verify field "Business Address" contains excel "excel:Business Address"
    Then I verify field "GST Registration Date" contains excel "excel:GST Registration Date"
    Then I verify field "Company Website" contains excel "excel:Company Website"
    Then I verify field "Industry ANZSIC Code" contains excel "excel:Industry ANZSIC Code"
    Then I verify field "Industry Classification" contains excel "excel:Industry Classification"
    Then I verify field "Business Background" contains excel "excel:Business Background"
    Then I verify field "Asset Purpose" contains excel "excel:Asset Purpose"
    #  Financial Details verification
    Then I verify field "Income" contains excel "excel:Income"
    Then I verify field "Expenses" contains excel "excel:Expenses"
    Then I verify field "Income Frequency" contains excel "excel:Income Frequency"
    Then I verify field "Expenses Frequency" contains excel "excel:Expenses Frequency"
#  Owners - Individuals Details verification
    Then I verify text "Applications without a Director's Guarantee will require further assessment, you will be required to provide 3 years worth of financial statements." is present
    Then I verify field "First Name" contains excel "excel:First Name"
    Then I verify field "Last Name" contains excel "excel:Last Name"
    Then I verify field "Roles" contains excel "excel:Roles"
    Then I verify field "Citizenship Status" contains excel "excel:Citizenship Status"
    Then I verify field "Residential Status" contains excel "excel:Residential Status"
    Then I verify field "Gender" contains excel "excel:Gender"
    Then I verify field "Residential Address" contains excel "excel:Residential Address"
    Then I verify field "Phone Number[2]" contains excel "excel:Phone Number"
    Then I verify field "Email" contains excel "excel:Email"
    Then I verify field "License Type" contains excel "excel:License Type"
    Then I verify field "License Class" contains excel "excel:License Class"
    Then I verify field "License State" contains excel "excel:License State"
    Then I verify field "Licence Number" contains excel "excel:Drivers Licence Number"
    #  Company Information 1 Details verification
    Then I verify text "Company 1" is present
    Then I verify field "ABN[3]" contains "66004759611"
    Then I verify field "ACN[2]" contains "004759611"
    Then I verify field "Company Name[2]" contains "HONDA AUSTRALIA PTY. LTD."
    Then I verify field "Roles[2]" contains "Shareholder"
    #  Owners - Trusts 1 Details verification
    Then I verify text "Trust 1" is present
    Then I verify field "ABN[4]" contains "45004189708"
    Then I verify field "Trust Name" contains "COLES SUPERMARKETS AUSTRALIA PTY LTD"
    Then I verify field "Roles[3]" contains "Guarantor"
#  Right side pane Details verification
    Then I verify text "Overall Decision" is present
    Then I verify text "Owner" is present
    Then I verify text "Funding Value" is present
    Then I verify text "$50,355.91" is present
    Then I verify text "Monthly Repayment" is present
    Then I verify text "$1,111.36" is present
    Then I verify text "Customer Tier" is present
    Then I verify text "Application Criteria" is present
    Then I verify text "Low-Doc" is present
    #   Verifying content on 'Credit Rules'
    Then I click on record view "Credit Rules"
    Then I verify grid "" column "Name" row "[1]" contains "ABN Age"
    Then I verify grid "" column "Rule Description" row "[1]" contains "ABN age is older than 1 year"
    Then I verify grid "" column "Result" row "[1]" contains "Approved"
    Then I verify grid "" column "Name" row "[2]" contains "Max Loan Amount"
    Then I verify grid "" column "Rule Description" row "[2]" contains "Total Loan Amount is less than $200,000"
    Then I verify grid "" column "Result" row "[2]" contains "Approved"
    Then I verify grid "" column "Name" row "[3]" contains "Credit File Age"
    Then I verify grid "" column "Rule Description" row "[3]" contains "Credit file age is equal to or greater than 12 months"
    Then I verify grid "" column "Value" row "[3]" contains "-"
    Then I verify grid "" column "Result" row "[3]" contains "Referred"
    Then I verify grid "" column "Name" row "[4]" contains "Credit File Activity"
    Then I verify grid "" column "Rule Description" row "[4]" contains "Credit file has activity recorded in the past 24 months from date of submission for current credit application"
    Then I verify grid "" column "Value" row "[4]" contains "-"
    Then I verify grid "" column "Result" row "[4]" contains "Referred"
    Then I verify grid "" column "Name" row "[5]" contains "Adverse Credit File"
    Then I verify grid "" column "Rule Description" row "[5]" contains "Applicant has no adverse on their credit file"
    Then I verify grid "" column "Value" row "[5]" contains "-"
    Then I verify grid "" column "Result" row "[5]" contains "Referred"
    Then I verify grid "" column "Name" row "[6]" contains "Lending Enquiries"
    Then I verify grid "" column "Rule Description" row "[6]" contains "Applicant has made more than 5 lending enquiries in the past 30 days and more than 20 in the last 180 days. "
    Then I verify grid "" column "Value" row "[6]" contains "-"
    Then I verify grid "" column "Result" row "[6]" contains "Referred"
    Then I verify grid "" column "Name" row "[7]" contains "Court Writs/Actions"
    Then I verify grid "" column "Rule Description" row "[7]" contains "Applicant has no Court Writ and/or Court Action on their credit file"
    Then I verify grid "" column "Value" row "[7]" contains "-"
    Then I verify grid "" column "Result" row "[7]" contains "Referred"
    Then I verify grid "" column "Name" row "[8]" contains "Credit Score (Tier A)"
    Then I verify grid "" column "Rule Description" row "[8]" contains "Credit Score is greater than 549"
    Then I verify grid "" column "Value" row "[8]" contains "-"
    Then I verify grid "" column "Result" row "[8]" contains "Referred"
    Then I verify grid "" column "Name" row "[9]" contains "ASIC File Status"
    Then I verify grid "" column "Rule Description" row "[9]" contains "Applicant ASIC File Status is 'Pending'"
    Then I verify grid "" column "Value" row "[9]" contains "False"
    Then I verify grid "" column "Result" row "[9]" contains "Approved"
    Then I verify grid "" column "Name" row "[10]" contains "Equifax - Individual Guarantor"
    Then I verify grid "" column "Rule Description" row "[10]" contains "Individual guarantors have been identified. Please view the associated Consumer and Commercial Report"
    Then I verify grid "" column "Value" row "[10]" contains "True"
    Then I verify grid "" column "Result" row "[10]" contains "Referred"
    Then I verify grid "" column "Name" row "[11]" contains "Green ID - Identity Verification"
    Then I verify grid "" column "Rule Description" row "[11]" contains "Identity verification pass on GreenID"
    Then I verify grid "" column "Value" row "[11]" contains "True"
    Then I verify grid "" column "Result" row "[11]" contains "Approved"
    Then I verify grid "" column "Name" row "[12]" contains "Green ID - PEP/Sanction check"
    Then I verify grid "" column "Rule Description" row "[12]" contains "No match found on PEP/Sanctions check"
    Then I verify grid "" column "Value" row "[12]" contains "True"
    Then I verify grid "" column "Result" row "[12]" contains "Approved"
    Then I verify grid "" column "Name" row "[13]" contains "Beneficial Owners Review Required"
    Then I verify grid "" column "Rule Description" row "[13]" contains "Applicant is a private company with at least one organisation listed as a shareholder. Please review the Beneficial Owners Report"
    Then I verify grid "" column "Value" row "[13]" contains "False"
    Then I verify grid "" column "Result" row "[13]" contains "Approved"
    Then I verify grid "" column "Name" row "[14]" contains "Company Guarantors"
    Then I verify grid "" column "Rule Description" row "[14]" contains "At least one guarantor has been identified as a company. Please review the guarantors Company Scored Enquiry Report"
    Then I verify grid "" column "Value" row "[14]" contains "False"
    Then I verify grid "" column "Result" row "[14]" contains "Approved"
    Then I verify grid "" column "Name" row "[15]" contains "ANZSIC Code"
    Then I verify grid "" column "Rule Description" row "[15]" contains "ANZSIC Industry classification does not meet ORIX policy"
    Then I verify grid "" column "Value" row "[15]" contains "False"
    Then I verify grid "" column "Result" row "[15]" contains "Approved"
    Then I verify grid "" column "Name" row "[16]" contains "Mercantile Agent Enquiries"
    Then I verify grid "" column "Rule Description" row "[16]" contains "Applicant has no  Mercantile Agent Enquiries < 12 months on their credit file"
    Then I verify grid "" column "Value" row "[16]" contains "False"
    Then I verify grid "" column "Result" row "[16]" contains "Referred"
    Then I verify grid "" column "Name" row "[17]" contains "Payment Defaults"
    Then I verify grid "" column "Rule Description" row "[17]" contains "Applicant has no Payment Defaults on their credit file"
    Then I verify grid "" column "Value" row "[17]" contains "True"
    Then I verify grid "" column "Result" row "[17]" contains "Approved"
    Then I verify grid "" column "Name" row "[18]" contains "Directors Adverse"
    Then I verify grid "" column "Rule Description" row "[18]" contains "Applicant has no  Company Director's Adverse on their credit file"
    Then I verify grid "" column "Value" row "[18]" contains "False"
    Then I verify grid "" column "Result" row "[18]" contains "Referred"
    Then I verify grid "" column "Name" row "[19]" contains "Directors Adverse (Related Entity)"
    Then I verify grid "" column "Rule Description" row "[19]" contains "Applicant has no Company Director's Related Entity Adverse on their credit file"
    Then I verify grid "" column "Value" row "[19]" contains "False"
    Then I verify grid "" column "Result" row "[19]" contains "Referred"
    Then I verify grid "" column "Name" row "[20]" contains "External Administrators"
    Then I verify grid "" column "Rule Description" row "[20]" contains "Applicant has no  External Administrators on their credit file"
    Then I verify grid "" column "Value" row "[20]" contains "True"
    Then I verify grid "" column "Result" row "[20]" contains "Approved"
    Then I verify grid "" column "Name" row "[21]" contains "Petitions"
    Then I verify grid "" column "Rule Description" row "[21]" contains "Applicant has no Petitions on their credit file"
    Then I verify grid "" column "Value" row "[21]" contains "True"
    Then I verify grid "" column "Result" row "[21]" contains "Approved"
    Then I verify grid "" column "Name" row "[22]" contains "Company Sub-Class"
    Then I verify grid "" column "Rule Description" row "[22]" contains "Applicant ASIC File Sub-Class is 'Proprietary Company'"
    Then I verify grid "" column "Value" row "[22]" contains "False"
    Then I verify grid "" column "Result" row "[22]" contains "Referred"
    Then I verify grid "" column "Name" row "[23]" contains "Application Criteria"
    Then I verify grid "" column "Rule Description" row "[23]" contains "The Application falls under the Low Doc criteria"
    Then I verify grid "" column "Value" row "[23]" contains "True"
    Then I verify grid "" column "Result" row "[23]" contains "Approved"
    Then I verify grid "" column "Name" row "[24]" contains "Luxury Vehicle (New)"
    Then I verify grid "" column "Rule Description" row "[24]" contains "Asset being financed is a New Passenger Car valued over $160K."
    Then I verify grid "" column "Value" row "[24]" contains "False"
    Then I verify grid "" column "Result" row "[24]" contains "Approved"
    Then I verify grid "" column "Name" row "[25]" contains "NZ Citizen"
    Then I verify grid "" column "Rule Description" row "[25]" contains "An Individual with NZ Citizenship has been identified"
    Then I verify grid "" column "Value" row "[25]" contains "False"
    Then I verify grid "" column "Result" row "[25]" contains "Approved"
    Then I verify grid "" column "Name" row "[26]" contains "Overall Decision"
    Then I verify grid "" column "Result" row "[26]" contains "Referred"
    Then I click on button "Individual Guarantor - John Wickner"
    Then I wait for "2" seconds
    Then I verify grid "" column "Name" row "[1]" contains "Credit File Age"
    Then I verify grid "" column "Rule Description" row "[1]" contains "Credit file age is equal to or greater than 12 months"
    Then I verify grid "" column "Result" row "[1]" contains "Referred"
    Then I verify grid "" column "Name" row "[2]" contains "Overall Decision"
    Then I verify grid "" column "Result" row "[2]" contains "Referred"
    Then I click on record view "Identity Verification - Applicant"
#    Verifying content on 'Identity Verification - Applicant'
    Then I verify text "This application has not initiated their Identity Verification" is present
    Then I click on record view "Identity Verification - Proprietors"
    Then I verify text "No additional individuals have listed on this application have initiated their Identity Verification" is present
#    Verifying content on 'Identity Verification - Proprietors'
    Then I click on record view "Credit Report - Applicant"
#    Verifying content on 'Credit Report - Applicant'
    Then I verify text "No Equifax Credit Reports to Display for this application." is present
    Then I click on record view "Beneficial Owner Report - Applicant"
    Then I click on record view "Credit Report - Guarantors"
    Then I verify grid "" column "Name of the Guarantor" row "[1]" contains "John Wickner"
    Then I verify grid "" column "Credit Report Name(s)" row "[1]" contains "Equifax Commercial Individual Report"
    Then I verify grid "" column "Status" row "[1]" contains "Success"
    Then I click on record view "Document Extraction"
    Then I verify text "No items available" is present
    Then I click on record view "Documents"
#    Verifying content on 'Documents'
    Then I verify text "Uploaded Documents" is present
    Then I verify grid "" column "Document Name" row "[1]" contains "Privacy_Consent_Form.pdf"
    Then I verify grid "" column "Document Type" row "[1]" contains "Privacy Consent Form"
    Then I verify grid "" column "Uploaded By" row "[1]" contains "Automation Introducer"
    Then I click on record view "Communications"
    Then I verify text "No items available" is present
    Then I click on record view "Event History"
    Then I wait for "3" seconds
#    Verifying content on 'Event History'
    Then I verify text "Assigned Application" is present
    Then I click on record view "Quote Details"
#    Verifying content on 'Quote Details'
    Then I verify text "Operating Lease" is present
    Then I verify text "HONDA CR-V" is present
    Then I verify field "Total Asset Cost" contains excel "excel:Total Asset Cost (incl. GST)"
    Then I verify field "GST" contains excel "excel:Total GST"
    Then I verify field "Total Cost of Lease" contains excel "excel:Total Cost of Lease"
    Then I verify field "Monthly Rental" contains excel "excel:Monthly Rental"
    Then I verify field "Specific Asset" contains excel "excel:Specific Asset"
    Then I verify field "New Asset" contains excel "excel:New Asset"
    Then I verify field "Pricing Type" contains excel "excel:Pricing Type"
    Then I verify field "Asset Type" contains excel "excel:Asset Type"
    Then I verify field "Monthly GST" contains excel "excel:Monthly GST"
    Then I verify field "Total GST" contains excel "excel:Total GST"
    Then I verify field "Residual Percentage" contains excel "excel:Residual Percentage"
    Then I verify field "Asset Category[2]" contains excel "excel:Vehicle or Asset Category"
    Then I verify field "Business" contains excel "excel:Company Name"
    Then I verify field "Introducer" contains "Dandenong Mits Pty Ltd"
    Then I verify field "Annual Usage" contains excel "excel:Annual Usage"
    Then I verify field "Discounts (excl GST)" contains excel "excel:Discounts (excl GST)"
    Then I verify field "Registration fee (excl GST)" contains excel "excel:Registration Fee (excl GST)"
    Then I verify field "Delivery State" contains excel "excel:Delivery State"
    Then I verify field "Status" contains excel "excel:Status"
    Then I verify field "Dealer Quote Document" contains excel "excel:Dealer Quote Document"
    Then I click on record view "Summary"
    Then I click on button "Update Credit Decision"
    Then I verify field "Decision" does not contain value "Conditional Approval"
    Then I verify field "Decision" does not contain value "Declined"
    Then I populate field "Decision" with excel "excel:Decision"
    Then I populate field "Allocated Officer for Final Decision" with excel "excel:Credit Officer"
    Then I populate field "Conditions" with excel "excel:Conditions of Approval"
    Then I click on button "Submit"
    Then I verify text "Overall Decision" is present
    Then I verify text "Recommend Conditional Approval" is present
    Then I verify text "Copy of current council rates notice to be provided to confirm property ownership." is present

  Scenario: TC004_Trust_Verify creditApprover is able overwrite credit decision for Trust
    Given I setup environment and login with role "creditApprover"
    Given I load test data for "TC004" from "04_SMB_End2End"
    When I click on record from excel "excel:Application Number"
#  Applicant Company Details verification
    Then I verify field "Company Name" contains excel "excel:Company Name"
    Then I verify field "ABN" contains excel "excel:ABN"
    Then I verify field "ACN" contains excel "excel:ACN"
    Then I verify field "Business Name" contains excel "excel:Registered Business Name"
    Then I verify field "Business Address" contains excel "excel:Business Address"
    Then I verify field "GST Registration Date" contains excel "excel:GST Registration Date"
    Then I verify field "Company Website" contains excel "excel:Company Website"
    Then I verify field "Industry ANZSIC Code" contains excel "excel:Industry ANZSIC Code"
    Then I verify field "Industry Classification" contains excel "excel:Industry Classification"
    Then I verify field "Business Background" contains excel "excel:Business Background"
    Then I verify field "Asset Purpose" contains excel "excel:Asset Purpose"
    Then I verify text "Overall Decision" is present
    Then I verify text "Recommend Conditional Approval" is present
    #  Financial Details verification
    Then I verify field "Income" contains excel "excel:Income"
    Then I verify field "Expenses" contains excel "excel:Expenses"
    Then I verify field "Income Frequency" contains excel "excel:Income Frequency"
    Then I verify field "Expenses Frequency" contains excel "excel:Expenses Frequency"
#  Owners - Individuals Details verification
    Then I verify text "Applications without a Director's Guarantee will require further assessment, you will be required to provide 3 years worth of financial statements." is present
    Then I verify field "First Name" contains excel "excel:First Name"
    Then I verify field "Last Name" contains excel "excel:Last Name"
    Then I verify field "Roles" contains excel "excel:Roles"
    Then I verify field "Citizenship Status" contains excel "excel:Citizenship Status"
    Then I verify field "Residential Status" contains excel "excel:Residential Status"
    Then I verify field "Gender" contains excel "excel:Gender"
    Then I verify field "Residential Address" contains excel "excel:Residential Address"
    Then I verify field "Phone Number[2]" contains excel "excel:Phone Number"
    Then I verify field "Email" contains excel "excel:Email"
    Then I verify field "License Type" contains excel "excel:License Type"
    Then I verify field "License Class" contains excel "excel:License Class"
    Then I verify field "License State" contains excel "excel:License State"
    Then I verify field "Licence Number" contains excel "excel:Drivers Licence Number"
    #  Company Information 1 Details verification
    Then I verify text "Company 1" is present
    Then I verify field "ABN[3]" contains "66004759611"
    Then I verify field "ACN[2]" contains "004759611"
    Then I verify field "Company Name[2]" contains "HONDA AUSTRALIA PTY. LTD."
    Then I verify field "Roles[2]" contains "Shareholder"
    #  Owners - Trusts 1 Details verification
    Then I verify text "Trust 1" is present
    Then I verify field "ABN[4]" contains "45004189708"
    Then I verify field "Trust Name" contains "COLES SUPERMARKETS AUSTRALIA PTY LTD"
    Then I verify field "Roles[3]" contains "Guarantor"
#  Right side pane Details verification
    Then I verify text "Overall Decision" is present
    Then I verify text "Owner" is present
    Then I verify text "Funding Value" is present
    Then I verify text "Monthly Repayment" is present
    Then I verify text "Customer Tier" is present
    Then I verify text "Application Criteria" is present
    Then I verify text "Low-Doc" is present
    #   Verifying content on 'Credit Rules'
    Then I click on record view "Credit Rules"
    Then I verify grid "" column "Name" row "[1]" contains "ABN Age"
    Then I verify grid "" column "Rule Description" row "[1]" contains "ABN age is older than 1 year"
    Then I verify grid "" column "Result" row "[1]" contains "Approved"
    Then I verify grid "" column "Name" row "[2]" contains "Max Loan Amount"
    Then I verify grid "" column "Rule Description" row "[2]" contains "Total Loan Amount is less than $200,000"
    Then I verify grid "" column "Result" row "[2]" contains "Approved"
    Then I verify grid "" column "Name" row "[3]" contains "Credit File Age"
    Then I verify grid "" column "Rule Description" row "[3]" contains "Credit file age is equal to or greater than 12 months"
    Then I verify grid "" column "Value" row "[3]" contains "-"
    Then I verify grid "" column "Result" row "[3]" contains "Referred"
    Then I verify grid "" column "Name" row "[4]" contains "Credit File Activity"
    Then I verify grid "" column "Rule Description" row "[4]" contains "Credit file has activity recorded in the past 24 months from date of submission for current credit application"
    Then I verify grid "" column "Value" row "[4]" contains "-"
    Then I verify grid "" column "Result" row "[4]" contains "Referred"
    Then I verify grid "" column "Name" row "[5]" contains "Adverse Credit File"
    Then I verify grid "" column "Rule Description" row "[5]" contains "Applicant has no adverse on their credit file"
    Then I verify grid "" column "Value" row "[5]" contains "-"
    Then I verify grid "" column "Result" row "[5]" contains "Referred"
    Then I verify grid "" column "Name" row "[6]" contains "Lending Enquiries"
    Then I verify grid "" column "Rule Description" row "[6]" contains "Applicant has made more than 5 lending enquiries in the past 30 days and more than 20 in the last 180 days. "
    Then I verify grid "" column "Value" row "[6]" contains "-"
    Then I verify grid "" column "Result" row "[6]" contains "Referred"
    Then I verify grid "" column "Name" row "[7]" contains "Court Writs/Actions"
    Then I verify grid "" column "Rule Description" row "[7]" contains "Applicant has no Court Writ and/or Court Action on their credit file"
    Then I verify grid "" column "Value" row "[7]" contains "-"
    Then I verify grid "" column "Result" row "[7]" contains "Referred"
    Then I verify grid "" column "Name" row "[8]" contains "Credit Score (Tier A)"
    Then I verify grid "" column "Rule Description" row "[8]" contains "Credit Score is greater than 549"
    Then I verify grid "" column "Value" row "[8]" contains "-"
    Then I verify grid "" column "Result" row "[8]" contains "Referred"
    Then I verify grid "" column "Name" row "[9]" contains "ASIC File Status"
    Then I verify grid "" column "Rule Description" row "[9]" contains "Applicant ASIC File Status is 'Pending'"
    Then I verify grid "" column "Value" row "[9]" contains "False"
    Then I verify grid "" column "Result" row "[9]" contains "Approved"
    Then I verify grid "" column "Name" row "[10]" contains "Equifax - Individual Guarantor"
    Then I verify grid "" column "Rule Description" row "[10]" contains "Individual guarantors have been identified. Please view the associated Consumer and Commercial Report"
    Then I verify grid "" column "Value" row "[10]" contains "True"
    Then I verify grid "" column "Result" row "[10]" contains "Referred"
    Then I verify grid "" column "Name" row "[11]" contains "Green ID - Identity Verification"
    Then I verify grid "" column "Rule Description" row "[11]" contains "Identity verification pass on GreenID"
    Then I verify grid "" column "Value" row "[11]" contains "True"
    Then I verify grid "" column "Result" row "[11]" contains "Approved"
    Then I verify grid "" column "Name" row "[12]" contains "Green ID - PEP/Sanction check"
    Then I verify grid "" column "Rule Description" row "[12]" contains "No match found on PEP/Sanctions check"
    Then I verify grid "" column "Value" row "[12]" contains "True"
    Then I verify grid "" column "Result" row "[12]" contains "Approved"
    Then I verify grid "" column "Name" row "[13]" contains "Beneficial Owners Review Required"
    Then I verify grid "" column "Rule Description" row "[13]" contains "Applicant is a private company with at least one organisation listed as a shareholder. Please review the Beneficial Owners Report"
    Then I verify grid "" column "Value" row "[13]" contains "False"
    Then I verify grid "" column "Result" row "[13]" contains "Approved"
    Then I verify grid "" column "Name" row "[14]" contains "Company Guarantors"
    Then I verify grid "" column "Rule Description" row "[14]" contains "At least one guarantor has been identified as a company. Please review the guarantors Company Scored Enquiry Report"
    Then I verify grid "" column "Value" row "[14]" contains "False"
    Then I verify grid "" column "Result" row "[14]" contains "Approved"
    Then I verify grid "" column "Name" row "[15]" contains "ANZSIC Code"
    Then I verify grid "" column "Rule Description" row "[15]" contains "ANZSIC Industry classification does not meet ORIX policy"
    Then I verify grid "" column "Value" row "[15]" contains "False"
    Then I verify grid "" column "Result" row "[15]" contains "Approved"
    Then I verify grid "" column "Name" row "[16]" contains "Mercantile Agent Enquiries"
    Then I verify grid "" column "Rule Description" row "[16]" contains "Applicant has no  Mercantile Agent Enquiries < 12 months on their credit file"
    Then I verify grid "" column "Value" row "[16]" contains "False"
    Then I verify grid "" column "Result" row "[16]" contains "Referred"
    Then I verify grid "" column "Name" row "[17]" contains "Payment Defaults"
    Then I verify grid "" column "Rule Description" row "[17]" contains "Applicant has no Payment Defaults on their credit file"
    Then I verify grid "" column "Value" row "[17]" contains "True"
    Then I verify grid "" column "Result" row "[17]" contains "Approved"
    Then I verify grid "" column "Name" row "[18]" contains "Directors Adverse"
    Then I verify grid "" column "Rule Description" row "[18]" contains "Applicant has no  Company Director's Adverse on their credit file"
    Then I verify grid "" column "Value" row "[18]" contains "False"
    Then I verify grid "" column "Result" row "[18]" contains "Referred"
    Then I verify grid "" column "Name" row "[19]" contains "Directors Adverse (Related Entity)"
    Then I verify grid "" column "Rule Description" row "[19]" contains "Applicant has no Company Director's Related Entity Adverse on their credit file"
    Then I verify grid "" column "Value" row "[19]" contains "False"
    Then I verify grid "" column "Result" row "[19]" contains "Referred"
    Then I verify grid "" column "Name" row "[20]" contains "External Administrators"
    Then I verify grid "" column "Rule Description" row "[20]" contains "Applicant has no  External Administrators on their credit file"
    Then I verify grid "" column "Value" row "[20]" contains "True"
    Then I verify grid "" column "Result" row "[20]" contains "Approved"
    Then I verify grid "" column "Name" row "[21]" contains "Petitions"
    Then I verify grid "" column "Rule Description" row "[21]" contains "Applicant has no Petitions on their credit file"
    Then I verify grid "" column "Value" row "[21]" contains "True"
    Then I verify grid "" column "Result" row "[21]" contains "Approved"
    Then I verify grid "" column "Name" row "[22]" contains "Company Sub-Class"
    Then I verify grid "" column "Rule Description" row "[22]" contains "Applicant ASIC File Sub-Class is 'Proprietary Company'"
    Then I verify grid "" column "Value" row "[22]" contains "False"
    Then I verify grid "" column "Result" row "[22]" contains "Referred"
    Then I verify grid "" column "Name" row "[23]" contains "Application Criteria"
    Then I verify grid "" column "Rule Description" row "[23]" contains "The Application falls under the Low Doc criteria"
    Then I verify grid "" column "Value" row "[23]" contains "True"
    Then I verify grid "" column "Result" row "[23]" contains "Approved"
    Then I verify grid "" column "Name" row "[24]" contains "Luxury Vehicle (New)"
    Then I verify grid "" column "Rule Description" row "[24]" contains "Asset being financed is a New Passenger Car valued over $160K."
    Then I verify grid "" column "Value" row "[24]" contains "False"
    Then I verify grid "" column "Result" row "[24]" contains "Approved"
    Then I verify grid "" column "Name" row "[25]" contains "NZ Citizen"
    Then I verify grid "" column "Rule Description" row "[25]" contains "An Individual with NZ Citizenship has been identified"
    Then I verify grid "" column "Value" row "[25]" contains "False"
    Then I verify grid "" column "Result" row "[25]" contains "Approved"
    Then I verify grid "" column "Name" row "[26]" contains "Overall Decision"
    Then I verify grid "" column "Result" row "[26]" contains "Referred"
    Then I click on button "Individual Guarantor - John Wickner"
    Then I wait for "2" seconds
    Then I verify grid "" column "Name" row "[1]" contains "Credit File Age"
    Then I verify grid "" column "Rule Description" row "[1]" contains "Credit file age is equal to or greater than 12 months"
    Then I verify grid "" column "Result" row "[1]" contains "Referred"
    Then I verify grid "" column "Name" row "[2]" contains "Overall Decision"
    Then I verify grid "" column "Result" row "[2]" contains "Referred"
    Then I click on record view "Identity Verification - Applicant"
#    Verifying content on 'Identity Verification - Applicant'
    Then I verify text "This application has not initiated their Identity Verification" is present
    Then I click on record view "Identity Verification - Proprietors"
    Then I verify text "No additional individuals have listed on this application have initiated their Identity Verification" is present
#    Verifying content on 'Identity Verification - Proprietors'
    Then I click on record view "Credit Report - Applicant"
#    Verifying content on 'Credit Report - Applicant'
    Then I verify text "No Equifax Credit Reports to Display for this application." is present
    Then I click on record view "Beneficial Owner Report - Applicant"
    Then I click on record view "Credit Report - Guarantors"
    Then I verify grid "" column "Name of the Guarantor" row "[1]" contains "John Wickner"
    Then I verify grid "" column "Credit Report Name(s)" row "[1]" contains "Equifax Commercial Individual Report"
    Then I verify grid "" column "Status" row "[1]" contains "Success"
    Then I click on record view "Document Extraction"
    Then I verify text "No items available" is present
    Then I click on record view "Documents"
#    Verifying content on 'Documents'
    Then I verify text "Uploaded Documents" is present
    Then I verify grid "" column "Document Name" row "[1]" contains "Privacy_Consent_Form.pdf"
    Then I verify grid "" column "Document Type" row "[1]" contains "Privacy Consent Form"
    Then I verify grid "" column "Uploaded By" row "[1]" contains "Automation Introducer"
    Then I click on record view "Communications"
    Then I verify text "No items available" is present
    Then I click on record view "Event History"
#    Verifying content on 'Event History'
    Then I verify text "Credit Decision" is present
    Then I verify text "Assigned Application" is present
    Then I click on record view "Quote Details"
#    Verifying content on 'Quote Details'
    Then I verify text "Operating Lease" is present
    Then I verify text "HONDA CR-V" is present
    Then I verify field "Total Asset Cost" contains excel "excel:Total Asset Cost (incl. GST)"
    Then I verify field "GST" contains excel "excel:Total GST"
    Then I verify field "Total Cost of Lease" contains excel "excel:Total Cost of Lease"
    Then I verify field "Monthly Rental" contains excel "excel:Monthly Rental"
    Then I verify field "Specific Asset" contains excel "excel:Specific Asset"
    Then I verify field "New Asset" contains excel "excel:New Asset"
    Then I verify field "Pricing Type" contains excel "excel:Pricing Type"
    Then I verify field "Asset Type" contains excel "excel:Asset Type"
    Then I verify field "Monthly GST" contains excel "excel:Monthly GST"
    Then I verify field "Total GST" contains excel "excel:Total GST"
    Then I verify field "Residual Percentage" contains excel "excel:Residual Percentage"
    Then I verify field "Asset Category[2]" contains excel "excel:Vehicle or Asset Category"
    Then I verify field "Business" contains excel "excel:Company Name"
    Then I verify field "Introducer" contains "Dandenong Mits Pty Ltd"
    Then I verify field "Annual Usage" contains excel "excel:Annual Usage"
    Then I verify field "Discounts (excl GST)" contains excel "excel:Discounts (excl GST)"
    Then I verify field "Registration fee (excl GST)" contains excel "excel:Registration Fee (excl GST)"
    Then I verify field "Delivery State" contains excel "excel:Delivery State"
    Then I verify field "Status" contains excel "excel:Status"
    Then I verify field "Dealer Quote Document" contains excel "excel:Dealer Quote Document"
    Then I click on record view "Summary"
    Then I click on button "Update Credit Decision"
    Then I populate field "Decision" with excel "excel:Decision"
    Then I populate field "Conditions" with excel "excel:Conditions of Approval"
    Then I click on button "Submit"
    Then I verify text "Overall Decision" is present
    Then I verify text "Conditional Approval" is present
    Then I verify text "Copy of current council rates notice to be provided to confirm property ownership." is present